/* A packrat parser generated by PackCC 1.5.0 */

#ifndef PCC_INCLUDED_ORIGOTOC_H
#define PCC_INCLUDED_ORIGOTOC_H

enum PointerType {
  ptrData = 1
};

typedef struct TypeSpec {
  unsigned pointerType;
  char simpleTypeName[2048];
  unsigned elementCount;
} TypeSpec;
#ifdef __cplusplus
extern "C" {
#endif

typedef struct pcc_context_tag pcc_context_t;

pcc_context_t *pcc_create(void *auxil);
int pcc_parse(pcc_context_t *ctx, int *ret);
void pcc_destroy(pcc_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_ORIGOTOC_H */
